version: 0.1.0.{build}

image: Ubuntu

install:
    - sh: sudo apt-get update
    - sh: sudo apt-get install -y libblosc1

build: off

build_script:
  - ./gradlew build

after_test:
  - ./gradlew distZip

artifacts:
  - path: 'build\distributions\*.zip'
